services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TOKEN=${DISCORD_TOKEN}
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=bonking_data
    volumes:
      - ./src:/app
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bonking_data
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./001_init.sql:/docker-entrypoint-initdb.d/001_init.sql
    restart: always

volumes:
  pgdata:

